---
- name: scaffold-actor CI-CD
  hosts: cloud-local
  tasks:
    - name: 编译golang项目
      delegate_to: localhost
      shell: |
        export GOPROXY=https://goproxy.cn
        cd /Users/opensea/explore/goravel/scaffold
        GOOS=linux GOARCH=amd64 go build -o bin/scaffold-actor main.go

    - name: 拷贝可执行文件-1到远程机器
      copy:
        src: /Users/opensea/explore/goravel/scaffold/bin/scaffold-actor
        dest: /home/openland/project/scaffold/actor/exec1/scaffold-actor1
        mode: 0755

    - name: 拷贝可执行文件-2到远程机器
      copy:
        src: /Users/opensea/explore/goravel/scaffold/bin/scaffold-actor
        dest: /home/openland/project/scaffold/actor/exec2/scaffold-actor2
        mode: 0755

    - name: 停止原服务集群
      shell: |
        pkill -f scaffold-actor1 || true
        pkill -f scaffold-actor2 || true
      ignore_errors: yes

    - name: 启动服务1
      shell: |
        cd /home/openland/project/scaffold/actor/exec1
        nohup ./scaffold-actor1 >/dev/null 2>&1 &

    - name: 启动服务2
      shell: |
        cd /home/openland/project/scaffold/actor/exec2
        nohup ./scaffold-actor2 >/dev/null 2>&1 &